import AdminHeader from './components/AdminHeader'
import '../globals.css'
import { Inter } from 'next/font/google'
import AdminSidebar from './components/AdminSidebar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Admin Panel - Book Store',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AdminHeader/>
        <div className='flex flex-1 justify-center'>
            <div className='w-2/12'>
                <AdminSidebar/>
            </div>
            <div className='w-10/12'>
                {children}
            </div>
        </div>
        </body>
    </html>
  )
}
